### ISSUE TITLE
"... Google may penalize your website for using improper schema snippets.'

### ISSUE THREAD

**Issue by belgraveassociates** [axelerant/testimonials-widget#200]
We've been getting a message for a while inside the WordPress admin, "Testimonials Widget uses Review schema markup for the testimonials. A recent move by Google may penalize your website for using improper schema snippets. Please use Review schema at your own risk via Settings." Can anyone shed light on axelerant's position on this warning? What does Google consider an "improper schema snippet" and how do we avoid that with Testimonials Widget? The warning provides [this link](https://www.seroundtable.com/google-takes-action-on-flight-rich-snippet-markup-22029.html). But the linked article doesn't specifically mention Review schema. Thanks in advance for any information.

**Comment by subharanjanm** [comment]
Hi @belgraveassociates , Thanks for reaching out to us.

We recommend you disable the Review schema to comply with Google’s recommendations

This notice is a heads up that Google is beginning to penalize people for using improper snippets.

Testimonials Widget uses the Review schema because there actually is no such schema for Testimonials, at least not yet. There should be one in our opinion, though. Use of the Review schema for testimonials has been working perfectly fine, even now. But, because of the possibility of getting penalized by Google which may happen way down the road, we have now turned this option off by default for new users of our plugin and started showing the warning notice for the existing users of the plugin as a precautionary measure.
