### ISSUE TITLE
Version 4.0 fatal error

### ISSUE THREAD

**Issue by steveni1963** [axelerant/testimonials-widget#209]
[12-Jul-2020 13:22:21 UTC] PHP Warning:  require_once(/home/xxxxxx/public_html/wp-content/plugins/testimonials-widget/includes/libraries/testimonials-widget/testimonials-widget.php): failed to open stream: No such file or directory in /home/xxxxxx/public_html/wp-content/plugins/testimonials-widget/testimonials-widget.php on line 54

The folder structure is not how it is shown in the error message.

**Comment by saurabhsirdixit** [comment]
Thank you for reporting this issue. SVN ignored the testimonials widget folder and that causes the issue.
Please download this version directly from the git repo in the meantime I am working on the fix. Probably in 30 mins the official fix should be out. Thanks.
https://github.com/axelerant/testimonials-widget/archive/master.zip

**Comment by saurabhsirdixit** [comment]
I have released the 4.0.1 version of the plugin which should fix the issue you mentioned above. Please update the plugin to the latest version and let me know your feedback.

Also, don’t forget to read about the plugin changelog as this is a major release and we have released the Testimonials Widget Premium plugin as part of WordPress Plugin contribution so that everyone can take the benefits of its all the feature.

**Comment by steveni1963** [comment]
Thank you for the quick fix.  Works perfectly now.  
Cheers!
